package agens

import (
	"context"
	"errors"
	"fmt"

	"github.com/firebase/genkit/go/ai"
)

var (
	// ErrNilAgent is returned when an operation requires an Agent instance,
	// but a nil pointer was provided instead.
	ErrNilAgent = errors.New("agent cannot be nil")

	// ErrNilPipelineProcessor is returned when initializing a new pipeline,
	// but the required PipelineProcessor implementation is nil.
	ErrNilPipelineProcessor = errors.New("processor cannot be nil")
)

// PipelineProcessor defines the core lifecycle hooks required to process data
// through the pipeline. It requires implementations for converting the original input
// into a batch ID and an AI message, transforming a batch of messages into a format
// the agent can process, and handling the final output from the agent.
type PipelineProcessor[T any] interface {
	// OriginalInputToMessage converts the original input into a batch ID and an AI message.
	OriginalInputToMessage(ctx context.Context, state *PipelineState[T]) (string, *ai.Message, error)

	// BatchToInput transforms a batch of messages into a format the agent can process.
	BatchToInput(ctx context.Context, state *PipelineState[T]) (*Input, error)

	// HandleAgentResponse handles the final output generated by the agent.
	HandleAgentResponse(ctx context.Context, state *PipelineState[T]) error
}

// PipelineOptions allows developers to override the default behaviors of a pipeline.
// It provides custom function hooks for BatchMessages and Generate steps.
type PipelineOptions[T any] struct {
	BatchMessages func(ctx context.Context, state *PipelineState[T]) (bool, []*ai.Message, error)
	Generate      func(ctx context.Context, state *PipelineState[T]) (*ai.ModelResponse, error)
}

// Pipeline is a function type that executes the complete processing flow for a given input.
type Pipeline[T any] func(ctx context.Context, gateway GatewayRef, input T) (bool, error)

// NewPipeline initializes and returns a new Pipeline[T]. It orchestrates the entire flow
// using the provided PipelineProcessor and optional PipelineOptions. It manages the internal
// state transitions from the initial input, through message batching, to the final agent response generation.
func NewPipeline[T any](processor PipelineProcessor[T], opts *PipelineOptions[T]) (Pipeline[T], error) {
	if processor == nil {
		return nil, ErrNilPipelineProcessor
	}

	// Options
	cfg := &PipelineOptions[T]{
		BatchMessages: DefaultPipelineBatchMessages[T],
		Generate:      DefaultPipelineGenerate[T],
	}

	if opts != nil {
		if opts.BatchMessages != nil {
			cfg.BatchMessages = opts.BatchMessages
		}
		if opts.Generate != nil {
			cfg.Generate = opts.Generate
		}
	}

	// Runner
	runner := &pipelineRunner[T]{
		processor: processor,
		cfg:       cfg,
	}

	fn := func(ctx context.Context, gateway GatewayRef, input T) (bool, error) {
		state := &PipelineState[T]{
			gateway:       gateway,
			originalInput: input,
		}

		return runner.originalInputToMessage(ctx, state)
	}

	return fn, nil
}

// DefaultPipelineBatchMessages is the default handler for message batching. It checks if the gateway
// has a configured MessageBatcher; if so, it adds the current message to the batch and determines
// if the pipeline should continue processing based on the resulting batch size.
func DefaultPipelineBatchMessages[T any](ctx context.Context, state *PipelineState[T]) (bool, []*ai.Message, error) {
	var msgBatcher = state.Gateway().MessageBatcher()

	if msgBatcher == nil {
		return true, []*ai.Message{state.Message()}, nil
	}

	batch, err := msgBatcher.Add(ctx, state.BatchMessageID(), state.Message())
	if err != nil {
		return false, nil, fmt.Errorf("failed to add message to batch: %w", err)
	}

	shouldContinue := (len(batch) > 0)

	return shouldContinue, batch, nil
}

// DefaultPipelineGenerate is the default handler for generating an agent response. It retrieves the agent
// associated with the gateway and triggers its generation process using the current state's agent input.
func DefaultPipelineGenerate[T any](ctx context.Context, state *PipelineState[T]) (*ai.ModelResponse, error) {
	var agent = state.Gateway().Agent()
	if agent == nil {
		return nil, ErrNilAgent
	}

	resp, err := agent.Generate(ctx, state.AgentInput())
	if err != nil {
		return nil, fmt.Errorf("agent generation failed: %w", err)
	}

	return resp, nil
}
